field: 8a8f6d5f-7942-40ee-9714-c4c36fe15fc8 # Home Client List
fieldLayouts:
  2ff3ca5a-9b53-49ad-b2fa-03ef86db4566:
    tabs:
      -
        elements:
          -
            fieldUid: c58c2e59-0099-4463-ab88-6443163ad279 # Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  c58c2e59-0099-4463-ab88-6443163ad279: # Logo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: logo
    instructions: 'Please insert/upload client image or logo'
    name: Logo
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:9b3a76f3-b105-4ce0-aca9-277a6f69aac1' # Clients
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:7b72aba2-e12b-4132-b4eb-260b1a40116e' # user_uploads
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:9b3a76f3-b105-4ce0-aca9-277a6f69aac1' # Clients
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: client
name: Client
sortOrder: 1
