field: 41837668-480b-441a-a73f-6eec94086c50 # Studio Entry Gallery
fieldLayouts:
  a5b068f3-e6a3-4366-b83c-300645833895:
    tabs:
      -
        elements:
          -
            fieldUid: fe1a467b-577a-4a78-b441-a5ff6f1a53dd # Gallery Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  fe1a467b-577a-4a78-b441-a5ff6f1a53dd: # Gallery Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: galleryImage
    instructions: ''
    name: 'Gallery Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:45558769-ed6a-4115-b464-b62fe3b3bafa' # Studio Gallery Images 
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:7b72aba2-e12b-4132-b4eb-260b1a40116e' # user_uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: gallery
name: Gallery
sortOrder: 1
