field: 5c0240cb-90c8-477f-9b86-7ba1f03781fd # Home Box CTA
fieldLayouts:
  d21b30ab-d928-409e-8009-8f66df51f603:
    tabs:
      -
        elements:
          -
            fieldUid: 14f42d6b-a51a-4864-be13-69de9ff89927 # Service Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3d78b203-f35f-4d0b-b1b7-1a56dd78b8c6 # Service Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 77c36666-dcf3-4100-877b-2ffa2feed87f # Service Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eb4d5f14-381c-446e-8049-5f4635926952 # Service Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3d78b203-f35f-4d0b-b1b7-1a56dd78b8c6: # Service Content
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: serviceContent
    instructions: ''
    name: 'Service Content'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  14f42d6b-a51a-4864-be13-69de9ff89927: # Service Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: serviceTitle
    instructions: ''
    name: 'Service Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  77c36666-dcf3-4100-877b-2ffa2feed87f: # Service Background Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: serviceBackgroundImage
    instructions: ''
    name: 'Service Background Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:7b72aba2-e12b-4132-b4eb-260b1a40116e' # user_uploads
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:7b72aba2-e12b-4132-b4eb-260b1a40116e' # user_uploads
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:7b72aba2-e12b-4132-b4eb-260b1a40116e' # user_uploads
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  eb4d5f14-381c-446e-8049-5f4635926952: # Service Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: serviceLink
    instructions: ''
    name: 'Service Link'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: service
name: Service
sortOrder: 1
