field: 38fc3edc-8bd6-4939-9969-9c68e6bdced9 # About Gallery
fieldLayouts:
  6fb6ec4c-4c05-4b7c-9706-cb41922db0f8:
    tabs:
      -
        elements:
          -
            fieldUid: ee37ff69-f057-4b82-86bb-ae118b0baec4 # Staff Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  ee37ff69-f057-4b82-86bb-ae118b0baec4: # Staff Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: staffImage
    instructions: ''
    name: 'Staff Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:bbd5936e-5efc-41d6-a80f-a172d0b5f28d' # About Images
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:7b72aba2-e12b-4132-b4eb-260b1a40116e' # user_uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: staffImages
name: 'Staff Images'
sortOrder: 1
