fieldLayouts:
  83eae2ec-6e78-4878-80d2-abd061cd0492:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: studioGalleryImages
hasUrls: true
name: 'Studio Gallery Images '
settings:
  path: '@webroot/images/studios/studio_gallery_images'
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: craft\volumes\Local
url: /images/studios/studio_gallery_images
