columnSuffix: nnuzmztc
contentColumnType: text
fieldGroup: a01422a2-f817-474f-93de-9c468fb08e48 # Home Page
handle: homeCtaText
instructions: 'This is a call out in the middle of the page right after the two boxes with the fade text'
name: 'Home CTA Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
