columnSuffix: dsxatwsm
contentColumnType: text
fieldGroup: a01422a2-f817-474f-93de-9c468fb08e48 # Home Page
handle: homeCtaLinkText
instructions: 'Text that will display in the button. Try to keep this short.'
name: 'Home CTA Link Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
