columnSuffix: jhawaqtj
contentColumnType: text
fieldGroup: 54edfdbc-adee-4bbd-b8de-41f3d806d858 # Studios
handle: studioEntryContent
instructions: 'Text to go under the title/jumbo of the studio entry.'
name: 'Studio Entry Content'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: ''
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
