columnSuffix: nmckpgjr
contentColumnType: text
fieldGroup: 6967b4c7-2778-4944-9ccc-07ea690ed289 # Studio Index Page
handle: studioIndexTitle
instructions: 'This is the content that will go at the very top of the page'
name: 'Studio Index Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
