dateModified: 1637937552
email:
  fromEmail: vargasman11@gmail.com
  fromName: nmp
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    571f405c-9331-468d-8315-814035448ce0: nmp # nmp
    618f9dcc-db7c-4a59-a4f5-904a035dde44: Common # Common
    af749d3e-842b-44a9-8eab-3a82a5f7e956: nmp # nmp
system:
  edition: solo
  live: true
  name: nmp
  schemaVersion: 3.7.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
