defaultPlacement: end
enableVersioning: true
handle: aboutPage
name: 'About Page'
propagationMethod: all
siteSettings:
  af749d3e-842b-44a9-8eab-3a82a5f7e956: # nmp
    enabledByDefault: true
    hasUrls: true
    template: about\index.twig
    uriFormat: about
type: single
