defaultPlacement: end
enableVersioning: true
handle: ourWorkPage
name: 'Our Work Page'
propagationMethod: all
siteSettings:
  af749d3e-842b-44a9-8eab-3a82a5f7e956: # nmp
    enabledByDefault: true
    hasUrls: true
    template: work\index.twig
    uriFormat: work
type: single
